Refactor/atomic design pattern
UMC-EXTRA/extra-react-webview pull request #12
Opened 2024-12-10 14:47 UTC by geon-2

## ✨ Issue Number

- #9 #10 

## 🗂️ Details

- Atoms: 최하위 컴포넌트
- [ ] Button
- [ ] Text
- [ ] Wrapper
- Mocules: atom으로 구성된 컴포넌트
- [ ] Item
- [ ] CalendarItem
- [ ] StatusTag

- Button Components
- StarToggleButton: 즐겨찾기 버튼
- MainButton: submit 버튼

- Text Components
- Text: 기본 텍스트 (size, weight 등 커스텀 가능함)
- ThemeText: 테마 고유 텍스트 (자주 사용되는 텍스트가 지정됨)

- Mocules
- Item: 공고 리스트 아이템
- CalendarItem: 공고 캘린더 아이템 (날짜)
- StatusTag: 상태 표시 태그

- 'http://localhost:5173/theme-preview'으로 preview 확인 가능

## ✅ Need Review
- 삭제 가능한 코드의 여부
- 모듈로서의 적합성
- 추가적으로 필요한 기능 여부

## 📸 Screenshot
![Vite-React-TS-12-10-2024_11_07_PM](https://github.com/user-attachments/assets/67bf6ff3-474e-46de-9971-e1a003684ef2)

## 📚 Reference
[Atomic Design Pattern](https://velog.io/@blee94/React-Atomic-Pattern-%EC%95%84%ED%86%A0%EB%AF%B9-%EB%94%94%EC%9E%90%EC%9D%B8%ED%8C%A8%ED%84%B4-%EC%97%90-%EB%8C%80%ED%95%B4-ARABOZA)

2024-12-10 15:37 UTC, nyewon requested changes

2024-12-10 15:37 UTC, nyewon commented on src/components/atoms/Button.tsx
> +const StarToggleButton: React.FC<ButtonProps> = ({ onClick, isActive }) => {
함수형 컴포넌트에서 타입을 지정할 때 React.FC의 사용은 지양해야 한다고 알고 있습니다!

React.FC를 사용할 경우 기본적으로 children props가 포함되어 props 타입이 명확하지 않다는 단점이 있습니다. 컴포넌트에서 children을 사용하지 않는 경우에도 불필요하게 children이 props 타입에 포함되기 때문에 코드의 의도와 타입 정의가 불일치할 수 있습니다.

따라서 React.FC를 사용하는 것 보다
`const StarToggleButton = ({ onClick, isActive }: ButtonProps)`
이런식으로 props를 명시적으로 지정하는게 더 좋을 것 같습니다!

참고: https://velog.io/@yena1025/FunctionComponent-FC-%EC%82%AC%EC%9A%A9-%EC%A4%84%EC%9D%B4%EA%B8%B0-24jhm0wp

2024-12-11 01:39 UTC, goodbyebada commented on src/components/mocules/CalendarItem.tsx
> +          <Text size={16} weight={900}>
현재 CalendarItem 컴포넌트의 글자 크기가 props로 주입받는 방식이 아니라, 내부에서 고정값 16으로 설정되어 있네요!
화면 크기에 따라 글자 크기도 유동적으로 변경될 수 있도록, props로 size를 주입받는 방식은 어떨까요?

또한, 만약 props로 글자 크기를 전달받게 된다면, 아래와 같이 font size를 상수로 관리하는 방식을 추천합니다! fontsize를 통일하기도 쉽고 유지보수성이 높아질 것 같습니다
```js
const FONT_SIZE = {
  LARGE: 30,
  MEDIUM: 16,
  SMALL: 10,
};

// 사용 예시
<Text size={FONT_SIZE.SMALL} weight={900} />
```

2024-12-11 01:39 UTC, goodbyebada commented on src/components/mocules/Item.tsx
> + */
주석이 자세히 작성되어 있어 이해하기 쉽고, 다른 사람이 코드를 참고하거나 수정할 때 큰 도움이 될 것 같습니다! 👍

2024-12-11 01:39 UTC, goodbyebada commented on src/components/atoms/Text.tsx
> +  color: ${({ color, highlight }) => (highlight ? "#F5C001" : color || "#fff")};
현재 색깔이 문자열로 지정되어있습니다. 색깔도 상수화하는 것은 어떤가요?

```js
const COLORS = {
	HIGH_LIGHT : "#F5C001"
}

//사용시 
color: ${({ color, highlight }) => (highlight ? COLORS.HIGH_LIGHT : color || "#fff")};
```

이렇게 하면 디자인 변경으로 highlight 색상이 다른 색으로 바뀌어도 COLORS.HIGH_LIGHT의 값만 수정하면 일괄적으로 수정이 적용되는 장점이 있습니다.

저희끼리 highlight, main ,emphasis (강조)등 색과 명칭에 대해 합의 후 적용하는건 어떤가요?

2024-12-11 07:54 UTC, geon-2 commented on src/components/atoms/Text.tsx
> +  color: ${({ color, highlight }) => (highlight ? "#F5C001" : color || "#fff")};
좋은 의견인 것 같네요! 상수화는 테마 작업할 때 통일 시키려고 했는데, 회의 때 정리해서 통일시켜보죠!

2024-12-11 07:55 UTC, geon-2 commented on src/components/atoms/Button.tsx
> +const StarToggleButton: React.FC<ButtonProps> = ({ onClick, isActive }) => {
오 전혀 몰랐던 내용이네요. 알려주셔서 감사합니다! 이거는 바로 수정해서 올릴께요

2024-12-11 08:03 UTC, nyewon approved these changes
변경된 내용 확인했습니다! 고생하셨습니다 :)

2024-12-11 08:04 UTC, geon-2 commented on src/components/mocules/CalendarItem.tsx
> +          <Text size={16} weight={900}>
일단 숫자로 지정가능하도록 변경했어요. fontsize 통일하는 작업은 테마 작업하면서 추가할께요!

2024-12-11 09:08 UTC, goodbyebada approved these changes
확인했습니다. 👍

2024-12-11 09:09 UTC, merged